from django.db import models
from django.utils.translation import gettext_lazy as _

# List grad years to choose from
class GradYear(models.TextChoices):
    y_2022 = '2022', _('2022')
    y_2023 = '2023', _('2023')
    y_2024 = '2024', _('2024')
    y_2025 = '2025', _('2025')
    y_2026 = '2026', _('2026')
    y_2027 = '2027', _('2027')
    y_2028 = '2028', _('2028')
    y_2029 = '2029', _('2029')
    y_2030 = '2030', _('2030')

# List Majors to choose from
class Majors(models.TextChoices):
    aero = 'Aerospace Engineering', _('Aerospace Engineering')
    aaas = 'African American and African Studies', _('African American and African Studies')
    amer_stud = 'American Studies', _('American Studies')
    antro = 'Anthropology', _('Anthropology')
    archaeology = 'Archaeology', _('Archaeology')
    arch_hist = 'Architectural History', _('Architectural History')
    arch = 'Architecture', _('Architecture')
    astro = 'Astronomy', _('Astronomy')
    bio = 'Biology', _('Biology')
    bme = 'Biomedical Engineering', _('Biomedical Engineering')
    cheme = 'Chemical Engineering', _('Chemical Engineering')
    chem = 'Chemistry', _('Chemistry')
    civil = 'Civil Engineering', _('Civil Engineering')
    classics = 'Classics', _('Classics')
    cog_sci = 'Cognitive Science', _('Cognitive Science')
    comm = 'Commerce', _('Commerce')
    comp_lit = 'Comparative Literature', _('Comparative Literature')
    ce = 'Computer Engineering', _('Computer Engineering')
    cs = 'Computer Science', _('Computer Science')
    dance = 'Dance', _('Dance')
    drama = 'Drama', _('Drama')
    ec_ed = 'Early Childhood Education', _('Early Childhood Education')
    east_asian = 'East Asian Languages, Literatures and Culture', _('East Asian Languages, Literatures and Culture')
    econ = 'Economics', _('Economics')
    ee = 'Electrical Engineering', _('Electrical Engineering')
    e_ed = 'Elementary Education', _('Elementary Education')
    eng = 'Engineering Science', _('Engineering Science')
    english = 'English', _('English')
    env_sci = 'Environmental Sciences', _('Environmental Sciences')
    env_tp = 'Environmental Thought and Practice', _('Environmental Thought and Practice')
    french = 'French', _('French')
    german = 'German', _('German')
    german_stud = 'German Studies', _('German Studies')
    global_stud = 'Global Studies', _('Global Studies')
    hsm = 'Health Sciences Management', _('Health Sciences Management')
    hist = 'History', _('History')
    hist_art = 'History of Art', _('History of Art')
    hum_bio = 'Human Biology', _('Human Biology')
    inter = 'Interdisciplinary Studies', _('Interdisciplinary Studies')
    jewish = 'Jewish Studies', _('Jewish Studies')
    kin = 'Kinesiology', _('Kinesiology')
    latin_amer = 'Latin American Studies', _('Latin American Studies')
    ling = 'Linguistics', _('Linguistics')
    mse = 'Materials Science and Engineering', _('Materials Science and Engineering')
    math = 'Mathematics', _('Mathematics')
    meche = 'Mechanical Engineering', _('Mechanical Engineering')
    media = 'Media Studies', _('Media Studies')
    medieval_stud = 'Medieval Studies', _('Medieval Studies')
    south_asia = 'Middle Eastern and South Asian Languages and Cultures', _('Middle Eastern and South Asian Languages and Cultures')
    music = 'Music', _('Music')
    neuro = 'Neuroscience', _('Neuroscience')
    nursing = 'Nursing', _('Nursing')
    phil = 'Philosophy', _('Philosophy')
    phys = 'Physics', _('Physics')
    pol_soc_thought = 'Political and Social Thought', _('Political and Social Thought')
    pppl = 'Political Philosophy, Policy, and Law', _('Political Philosophy, Policy, and Law')
    poli = 'Politics', _('Politics')
    psych = 'Psychology', _('Psychology')
    relig = 'Religious Studies', _('Religious Studies')
    slavic = 'Slavic Languages and Literatures', _('Slavic Languages and Literatures')
    soc = 'Sociology', _('Sociology')
    span = 'Spanish', _('Spanish')
    spec_ed = 'Special Education', _('Special Education')
    speech = 'Speech Communication Disorders', _('Speech Communication Disorders')
    stat = 'Statistics', _('Statistics')
    studio_art = 'Studio Art', _('Studio Art')
    systems = 'Systems Engineering', _('Systems Engineering')
    uep = 'Urban and Environmental Planning', _('Urban and Environmental Planning')
    wgs = 'Women, Gender & Sexuality', _('Women, Gender & Sexuality')
    ysi = 'Youth & Social Innovation', _('Youth & Social Innovation')