# Generated by Django 3.2.7 on 2021-11-15 00:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_mnemonic', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('Aerospace Engineering', 'Aerospace Engineering'), ('African American and African Studies', 'African American and African Studies'), ('American Studies', 'American Studies'), ('Anthropology', 'Anthropology'), ('Archaeology', 'Archaeology'), ('Architectural History', 'Architectural History'), ('Architecture', 'Architecture'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Classics', 'Classics'), ('Cognitive Science', 'Cognitive Science'), ('Commerce', 'Commerce'), ('Comparative Literature', 'Comparative Literature'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Dance', 'Dance'), ('Drama', 'Drama'), ('Early Childhood Education', 'Early Childhood Education'), ('East Asian Languages, Literatures and Culture', 'East Asian Languages, Literatures and Culture'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Elementary Education', 'Elementary Education'), ('Engineering Science', 'Engineering Science'), ('English', 'English'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Thought and Practice', 'Environmental Thought and Practice'), ('French', 'French'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Studies', 'Global Studies'), ('Health Sciences Management', 'Health Sciences Management'), ('History', 'History'), ('History of Art', 'History of Art'), ('Human Biology', 'Human Biology'), ('Interdisciplinary Studies', 'Interdisciplinary Studies'), ('Jewish Studies', 'Jewish Studies'), ('Kinesiology', 'Kinesiology'), ('Latin American Studies', 'Latin American Studies'), ('Linguistics', 'Linguistics'), ('Materials Science and Engineering', 'Materials Science and Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Media Studies', 'Media Studies'), ('Medieval Studies', 'Medieval Studies'), ('Middle Eastern and South Asian Languages and Cultures', 'Middle Eastern and South Asian Languages and Cultures'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political and Social Thought', 'Political and Social Thought'), ('Political Philosophy, Policy, and Law', 'Political Philosophy, Policy, and Law'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Religious Studies', 'Religious Studies'), ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'), ('Sociology', 'Sociology'), ('Spanish', 'Spanish'), ('Special Education', 'Special Education'), ('Speech Communication Disorders', 'Speech Communication Disorders'), ('Statistics', 'Statistics'), ('Studio Art', 'Studio Art'), ('Systems Engineering', 'Systems Engineering'), ('Urban and Environmental Planning', 'Urban and Environmental Planning'), ('Women, Gender & Sexuality', 'Women, Gender & Sexuality'), ('Youth & Social Innovation', 'Youth & Social Innovation')], max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('grad_year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('pdf_file', models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.course')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
