# Generated by Django 3.2.8 on 2021-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('professor', models.CharField(max_length=50)),
                ('course_descrip', models.TextField()),
                ('lecture_times', models.TextField()),
            ],
        ),
    ]
