# Generated by Django 3.2.8 on 2021-10-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
