# Generated by Django 3.2.7 on 2021-10-28 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0003_rename_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_descrip',
            new_name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture_times',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
