# Generated by Django 3.2.7 on 2021-11-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0003_auto_20211114_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
