# Generated by Django 3.2.7 on 2021-11-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0005_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
