# Generated by Django 3.2.7 on 2021-11-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0005_auto_20211101_2030'),
        ('assignment_app', '0006_alter_pdf_pdf_file'),
    ]

    operations = [
    ]
